import { db, jobsTable, testimonialsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

const JOBS = [
  { title: "Senior Civil Engineer", location: "Perth, Australia", category: "Engineering", experienceLevel: "Senior (7+ years)", description: "Lead structural and civil works on a $400M infrastructure project in Western Australia. You will oversee a multidisciplinary team, manage subcontractors, and liaise directly with the client. RPEQ or equivalent registration required. Visa sponsorship and relocation package available.", salaryRange: "AUD $140,000 – $165,000 + Super + Allowances", isUrgent: true },
  { title: "Offshore Drilling Supervisor", location: "Bergen, Norway", category: "Oil & Gas", experienceLevel: "Senior (7+ years)", description: "Supervise daily drilling operations on a semi-submersible rig in the North Sea. Ensure compliance with NORSOK standards, manage crew of 25, and coordinate with the onshore team. OPITO BOSIET and IWCF Level 4 required. 28/28 rotation, FIFO from major EU cities.", salaryRange: "NOK 1,200,000 – 1,500,000 per year + Night Differential", isUrgent: true },
  { title: "Registered Nurse – ICU", location: "Manchester, United Kingdom", category: "Healthcare", experienceLevel: "Mid-level (3–6 years)", description: "Join an NHS trust in Manchester as a Band 6 ICU nurse. You will manage complex patients, mentor junior staff, and participate in quality improvement projects. NMC registration support provided. IELTS coaching and relocation allowance included.", salaryRange: "GBP £33,000 – £39,000 + NHS Benefits", isUrgent: false },
  { title: "Mining Superintendent – Open Pit", location: "Lae, Papua New Guinea", category: "Mining", experienceLevel: "Senior (7+ years)", description: "Oversee open-pit gold mining operations at a major Australasian joint venture. Responsibilities include blast planning, fleet management, and safety leadership for a team of 120. FIFO roster 28/28. Housing, meals, and return flights provided.", salaryRange: "USD $130,000 – $155,000 tax-advantaged + Full Camp Benefits", isUrgent: true },
  { title: "Mechanical Engineer – LNG Plant", location: "Gladstone, Australia", category: "Engineering", experienceLevel: "Mid-level (3–6 years)", description: "Support maintenance planning and reliability engineering for rotating and static equipment at an operational LNG facility. Experience with CMMS (SAP/Maximo) and pressure vessels essential. Contract initially 12 months with strong view to extension.", salaryRange: "AUD $120,000 – $135,000 + Allowances", isUrgent: false },
  { title: "Welding Inspector (CSWIP 3.1)", location: "Doha, Qatar", category: "Construction", experienceLevel: "Mid-level (3–6 years)", description: "Conduct weld quality inspections on a major petrochemical construction project. Verify WPS, PQR, and welder qualification records. Work closely with QA/QC teams and the client representative. CSWIP 3.1 or AWS CWI mandatory. Accommodation and transport provided.", salaryRange: "USD $4,500 – $5,500 per month + Accommodation + Transport", isUrgent: false },
  { title: "Maritime Chief Engineer – Bulk Carrier", location: "International Waters (Singapore Hub)", category: "Maritime", experienceLevel: "Senior (7+ years)", description: "Chief Engineer required for a 180,000 DWT Capesize bulk carrier operating on iron ore and coal routes. Oversee all engine room operations, maintenance budgets, and port-state inspections. Class 1 (Motor) Certificate of Competency essential.", salaryRange: "USD $10,000 – $12,500 per month", isUrgent: true },
  { title: "Electrical Engineer – Substation Projects", location: "Singapore", category: "Engineering", experienceLevel: "Mid-level (3–6 years)", description: "Manage substation design, testing, and commissioning for a national utilities operator expanding its 66/22kV network. PE registration (Singapore) or equivalent preferred. Strong EPC project background required. PR sponsorship pathway available for high performers.", salaryRange: "SGD $7,500 – $9,500 per month", isUrgent: false },
  { title: "Food & Beverage Manager", location: "Dubai, UAE", category: "Hospitality", experienceLevel: "Mid-level (3–6 years)", description: "Manage F&B operations across three outlets at a five-star resort on Palm Jumeirah. Lead a team of 60, oversee P&L, and maintain guest satisfaction scores. Degree in Hospitality Management preferred. Accommodation allowance and annual return flight included.", salaryRange: "AED $18,000 – $22,000 per month + Benefits", isUrgent: false },
  { title: "CNC Machinist – Automotive", location: "Stuttgart, Germany", category: "Manufacturing", experienceLevel: "Mid-level (3–6 years)", description: "Operate and set up 5-axis CNC machining centres producing precision automotive components. Read technical drawings, perform first-off inspections, and maintain equipment logs. EU Blue Card processing and German language support provided.", salaryRange: "EUR €3,800 – €4,600 per month + Shift Premium", isUrgent: false },
  { title: "Occupational Health & Safety Manager", location: "Riyadh, Saudi Arabia", category: "Construction", experienceLevel: "Senior (7+ years)", description: "Lead HSE for a $2B road infrastructure project across the Riyadh metropolitan region. Develop and implement safety management systems, conduct investigations, and report to the project director. NEBOSH International Diploma required. Family visa assistance available.", salaryRange: "USD $8,000 – $10,000 per month + Accommodation", isUrgent: true },
  { title: "Logistics Coordinator – Shipping", location: "Rotterdam, Netherlands", category: "Logistics & Supply Chain", experienceLevel: "Entry-level (0–2 years)", description: "Coordinate vessel scheduling, cargo booking, and customs documentation for a major bulk shipping operator. Liaise with port agents, charterers, and terminal operators across Europe and Asia. Strong English and a second European language preferred.", salaryRange: "EUR €2,800 – €3,400 per month", isUrgent: false },
  { title: "Heavy Equipment Operator – Excavator", location: "Riyadh, Saudi Arabia", category: "Construction", experienceLevel: "Mid-level (3–6 years)", description: "Operate Cat 390 and Liebherr R 9200 excavators on a major expressway project. Valid large excavator certification required. Accommodation, three meals daily, and medical insurance provided. Overtime available.", salaryRange: "USD $2,800 – $3,500 per month + Full Camp Benefits", isUrgent: false },
  { title: "Pipeline Integrity Engineer", location: "Calgary, Canada", category: "Oil & Gas", experienceLevel: "Mid-level (3–6 years)", description: "Support in-line inspection programs, defect assessment, and fitness-for-service evaluations on a 4,000 km high-pressure gas transmission network. Proficiency in RSTRENG, ACFM, and ILI data analysis required. PR sponsorship pathway available.", salaryRange: "CAD $110,000 – $130,000 per year + Benefits", isUrgent: true },
  { title: "Offshore Vessel Master – AHTS", location: "Aberdeen, United Kingdom", category: "Maritime", experienceLevel: "Senior (7+ years)", description: "Command an 18,000 BHP anchor-handling tug supply vessel operating in the North Sea and West Africa. STCW II/2 Master Unlimited, DP Unlimited, and AHTS endorsement required. 28/28 rotation with competitive leave pay.", salaryRange: "GBP £75,000 – £90,000 per year", isUrgent: false },
];

const TESTIMONIALS = [
  { name: "James Mwangi", role: "Civil Engineer", country: "Kenya → Australia", quote: "Bluestar Alliance placed me with a major infrastructure consortium in Perth within six weeks of my first enquiry. The team handled every document — my visa, work permit, even the flight — with zero stress on my end. Three years on, I'm a senior site engineer leading a $240 million bridge project. This agency genuinely changed my life.", avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg" },
  { name: "Maria Santos", role: "Registered Nurse", country: "Philippines → United Kingdom", quote: "After ten years working in Manila hospitals I wanted an international career. Bluestar's healthcare division matched me with an NHS trust in Manchester. They arranged my NMC registration support, IELTS coaching referral, and relocation allowance. I'm now a charge nurse in the ICU and earning four times my previous salary. I recommend them without hesitation.", avatarUrl: "https://randomuser.me/api/portraits/women/45.jpg" },
  { name: "Aleksandr Petrenko", role: "Mechanical Engineer", country: "Ukraine → Canada", quote: "I was sceptical at first — I'd seen too many agencies make empty promises. But Bluestar was transparent from day one: exact salary, contract terms, city, everything. I arrived in Calgary for a pipeline maintenance role and the employer already knew my background in detail. Six months later I received a permanent residency sponsorship. Professional in every sense.", avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg" },
  { name: "Fatima Al-Rashidi", role: "Hospitality Manager", country: "Jordan → UAE", quote: "Bluestar placed me as Food & Beverage Manager at a five-star resort in Dubai. The offer was negotiated above my expectations — better title, accommodation allowance, and an annual return flight. My regional director told me Bluestar sends the most thoroughly prepared candidates he's ever seen. That reputation reflects the real experience.", avatarUrl: "https://randomuser.me/api/portraits/women/62.jpg" },
  { name: "Kweku Asante", role: "Mining Superintendent", country: "Ghana → Papua New Guinea", quote: "I had 14 years of open-pit mining experience but couldn't break into international roles on my own. Bluestar identified a superintendent vacancy with a major gold mining company in PNG, prepared me for every stage of the interview process, and I started within 12 weeks. My package includes a housing allowance, FIFO rotation, and superannuation contributions. Outstanding service.", avatarUrl: "https://randomuser.me/api/portraits/men/54.jpg" },
  { name: "Nguyen Thi Lan", role: "CNC Machinist", country: "Vietnam → Germany", quote: "Bluestar's skilled trades division found me a precision machining role with a German automotive supplier in Stuttgart. They organised language training support and my EU Blue Card processing. The difference between Bluestar and the agencies I'd tried before is simple: they actually read your CV and match you properly. I've since referred three colleagues who are all placed.", avatarUrl: "https://randomuser.me/api/portraits/women/39.jpg" },
  { name: "Roberto Delgado", role: "Offshore Drilling Supervisor", country: "Mexico → Norway", quote: "Getting OPITO-certified roles on the Norwegian shelf is notoriously competitive. Bluestar's oil and gas team knew exactly which operators were hiring, coached me on the competency-based interviews, and had me on a rig in the North Sea within four months. The rotational schedule — 28 on / 28 off — lets me spend real time with my family. I couldn't be happier.", avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg" },
  { name: "Priya Krishnaswamy", role: "Electrical Engineer", country: "India → Singapore", quote: "I was a mid-level electrical engineer in Chennai looking for a regional move. Bluestar placed me with a utilities company in Singapore managing substation upgrades across the island. My salary doubled, the work-life balance is excellent, and Singapore's PR pathway is well within reach. The process from first call to offer letter was under eight weeks — genuinely efficient.", avatarUrl: "https://randomuser.me/api/portraits/women/26.jpg" },
  { name: "Thomas Osei-Bonsu", role: "Heavy Equipment Operator", country: "Ghana → Saudi Arabia", quote: "I operate large excavators and motor graders. Bluestar's industrial placement team found me a role on a massive road-building project in Riyadh. Accommodation and three meals a day are provided, the pay is excellent, and I'm sending money home every month. They also helped me renew my Caterpillar operator certifications before deployment — extra care you don't expect.", avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg" },
  { name: "Elena Marchetti", role: "Maritime Chief Officer", country: "Italy → International (Bulk Carrier)", quote: "After 12 years in the Italian merchant navy I wanted deep-sea bulk carrier experience. Bluestar Maritime connected me with a reputable Greek shipowner operating Capesize vessels. The flag state documentation and STCW refresher logistics were handled entirely by their maritime desk. I'm now on my third contract with the same owner — testament to the quality of the match.", avatarUrl: "https://randomuser.me/api/portraits/women/18.jpg" },
  { name: "Samuel Chirwa", role: "Welding Supervisor", country: "Zambia → Qatar", quote: "Bluestar's construction team placed me as a welding supervisor on a liquefied natural gas facility in Ras Laffan. My AWS and ASME certifications were exactly what the client needed. The agency negotiated overtime provisions I hadn't asked for and arranged my family's dependent visa simultaneously. In two years I've saved enough to build a home back in Lusaka.", avatarUrl: "https://randomuser.me/api/portraits/men/76.jpg" },
  { name: "Aiko Tanaka", role: "Logistics Coordinator", country: "Japan → Netherlands", quote: "I joined the global supply-chain team of a Rotterdam-based shipping conglomerate through Bluestar. The role involves coordinating vessel scheduling across Asia-Pacific and Europe — exactly the exposure I wanted. Bluestar prepared me with industry-specific interview questions and salary benchmarking data I could never have found on my own. Worth every step of the process.", avatarUrl: "https://randomuser.me/api/portraits/women/8.jpg" },
];

export async function seedDatabase(): Promise<void> {
  try {
    const [{ jobCount }] = await db.select({ jobCount: sql<number>`COUNT(*)::int` }).from(jobsTable);
    const [{ testimonialCount }] = await db.select({ testimonialCount: sql<number>`COUNT(*)::int` }).from(testimonialsTable);

    if (jobCount === 0) {
      logger.info("Seeding jobs table…");
      await db.insert(jobsTable).values(JOBS);
      logger.info({ count: JOBS.length }, "Jobs seeded");
    } else {
      logger.info({ jobCount }, "Jobs table already populated — skipping");
    }

    if (testimonialCount === 0) {
      logger.info("Seeding testimonials table…");
      await db.insert(testimonialsTable).values(TESTIMONIALS);
      logger.info({ count: TESTIMONIALS.length }, "Testimonials seeded");
    } else {
      logger.info({ testimonialCount }, "Testimonials table already populated — skipping");
    }
  } catch (err) {
    logger.error({ err }, "Seed failed — continuing server startup");
  }
}
